### ISSUE TITLE
Updated versions

### ISSUE THREAD

**Issue by eadesignro** [DavidLambauer/awesome-magento2#17]
Hi,

Take a look at this 2 and let me know what you think.

https://github.com/EaDesgin/magento2-pdf-generator2
https://github.com/EaDesgin/magento2-mobiledetect

Thanks,

**Comment by DavidLambauer** [comment]
Hi there,

thanks for your contribution. The modules you mentioned look great. Please give me some time to review them and add them to the list! I might apply some minor PR's. 

Greetings David

**Comment by DavidLambauer** [comment]
Hey, I just added your Extension! Thanks again for contributing.
