### ISSUE TITLE
Have a look to our Open Source elasticsearch implementation

### ISSUE THREAD

**Issue by romainruaud** [DavidLambauer/awesome-magento2#5]
Hello, and congratulations for compiling all those extensions.

You should take a look to our implementation of ElasticSearch which is available for both CE and EE for free, and also features merchandising tools (virtual categories, configurable boosts for search, and so on ...)

More details on our Github : https://github.com/Smile-SA/elasticsuite/

**Comment by DavidLambauer** [comment]
Hi @romainruaud, I will have a look on that (hopefully tonight)! 

Thanks for the recommendation!

**Comment by DavidLambauer** [comment]
Wow this Extension is well maintained! I will add this to the Search Section! Thanks for the recommendation!

**Comment by DavidLambauer** [comment]
Closed, because added.
