### ISSUE TITLE
[Links] Magento integrations with Adobe products

### ISSUE THREAD

**Issue by roma-glushko** [DavidLambauer/awesome-magento2#76]
Not sure where it's better to place these projects but Adobe started to create a couple of connectors with their products and Magento2:
- https://github.com/adobe/commerce-cif-magento-graphql
- https://github.com/magento/aep-launch
- https://github.com/magento/adobe-stock-integration

They might be useful for someone 😌

**Comment by DavidLambauer** [comment]
Makes sense! Feel free to add them!

**Comment by shopaalogics** [comment]
Now there are several adobe products that are integrated with adobe.  For example [Progressive Web App (PWA) for Magento 2](https://shop.aalogics.com/progressive-web-app-for-magento-2) is one the adobe product provided by them.

**Comment by shopaalogics** [comment]
Here is the link to Magento integrations with Adobe products. You will find [multiple extensions](https://shop.aalogics.com/extensions) for integrations.

**Comment by DavidLambauer** [comment]
@shopaalogics This is a link to a list of products of your company. This Repo is not for marketing purposes...
